Assignment 04

Name: Azizur Rahman

Date: 25 june 2026

Dataset info :

name : Garment_job_Risk_bulk_dataset
size : 20,300 rows x 15 columns

import important library

In [140]:
import numpy as np
import pandas as pd

In [141]:
df = pd.read_csv("/content/Garment_Job_Risk_bulk_dataset.csv")
df.head(5)

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low

**1. Missing Values Handling**

---
Problem Detection

In [142]:
df.isnull().sum()
df.isnull().mean()*100

Name                        0.00
Garment_Name                0.00
Experience_Years            0.00
Job_Role                    0.00
Working_Hours_Per_Week      0.00
Exposure_To_Chemicals      48.96
Machine_Use                18.16
Workstation_Ergonomics      0.00
Injury_History              0.00
Health_Condition            0.00
Safety_Training            17.52
Shift_Type                  0.00
Task_Rotation_Frequency     0.00
Job_Risk                    0.00
dtype: float64

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     2500 non-null   object
 1   Garment_Name             2500 non-null   object
 2   Experience_Years         2500 non-null   int64
 3   Job_Role                 2500 non-null   object
 4   Working_Hours_Per_Week   2500 non-null   int64
 5   Exposure_To_Chemicals    1276 non-null   object
 6   Machine_Use              2046 non-null   object
 7   Workstation_Ergonomics   2500 non-null   object
 8   Injury_History           2500 non-null   int64
 9   Health_Condition         2500 non-null   object
 10  Safety_Training          2062 non-null   object
 11  Shift_Type               2500 non-null   object
 12  Task_Rotation_Frequency  2500 non-null   object
 13  Job_Risk                 2500 non-null   object
dtypes: int64(3), object(11)
memory usage: 273.6+ KB

**Solutions**

*   Drop Rows
*   Drop Columns
*   Mean Imputation
*   Median Imputation
*   Mode Imputation
*   Forward Fill
*   Backward Fill

In [144]:
dfTaskOne = df.copy()

In [145]:
#Drop rows
dfTaskOne.dropna(inplace=True)
dfTaskOne.isnull().sum()

#no numeric columns have missing values,so we need to change categorical columns

dfTaskOne['Exposure_To_Chemicals'] = dfTaskOne['Exposure_To_Chemicals'].fillna(dfTaskOne['Exposure_To_Chemicals'].mode()[0])
dfTaskOne['Machine_Use'] = dfTaskOne['Machine_Use'].fillna(dfTaskOne['Machine_Use'].mode()[0])
dfTaskOne['Safety_Training'] = dfTaskOne['Safety_Training'].fillna(dfTaskOne['Safety_Training'].mode()[0])

**2. Duplicate Data Removal**

In [146]:
dfSecondTask = df.copy()

In [147]:
dfSecondTask.duplicated().sum()

np.int64(0)

There are no duplicate value so we dont need to do anything

**3. Wrong Format Fix**

---


Problem Detection

In [148]:
df.dtypes

Name                       object
Garment_Name               object
Experience_Years            int64
Job_Role                   object
Working_Hours_Per_Week      int64
Exposure_To_Chemicals      object
Machine_Use                object
Workstation_Ergonomics     object
Injury_History              int64
Health_Condition           object
Safety_Training            object
Shift_Type                 object
Task_Rotation_Frequency    object
Job_Risk                   object
dtype: object


*   dataset has no date formats
*   no need to chenge string to numeric
*   dont need normalize

**4. Inconsistent Labels**


---
Problem Detection

In [149]:
df["Job_Role"].unique()

array(['Packaging', 'Supervisor', 'Sewing', 'Ironing', 'Cutting',
       'Dyeing', 'Machine_Maintenance'], dtype=object)

In [150]:
df["Exposure_To_Chemicals"].unique()

array(['Medium', 'Low', 'High', nan], dtype=object)

In [151]:
df["Machine_Use"].unique()

array(['Light', nan, 'Heavy'], dtype=object)

In [152]:
df["Workstation_Ergonomics"].unique()

array(['Average', 'Good', 'Poor'], dtype=object)

In [153]:
df["Health_Condition"].unique()

array(['Healthy', 'Minor_Chronic', 'Serious_Chronic'], dtype=object)

In [154]:
df["Safety_Training"].unique()

array(['Basic', nan, 'Advanced'], dtype=object)

In [155]:
df["Shift_Type"].unique()

array(['Day', 'Night', 'Evening'], dtype=object)

In [156]:
df["Task_Rotation_Frequency"].unique()

array(['Occasional', 'Frequent', 'Rare'], dtype=object)

In [157]:
df["Job_Risk"].unique()

array(['Low', 'Medium', 'High'], dtype=object)

**all columns are consistent,so we dont need to any change**

**5. Outlier Detection & Handling**

---

Problem Detection


Methods:

- Boxplot
- IQR
- Z-Score
- Domain Rules

Example:

Age < 0
Salary > 10M

### Solutions

- Remove
- Cap (Winsorization)
- Log Transform

In [158]:
#for experience year column

Q1 = df["Experience_Years"].quantile(0.25)
Q3 = df["Experience_Years"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Experience_Years"] < lower) |
    (df["Experience_Years"] > upper)
]

outliers
print(len(outliers))

0

In [159]:
#for Working_Hours_Per_Week columns
Q1 = df["Working_Hours_Per_Week"].quantile(0.25)
Q3 = df["Working_Hours_Per_Week"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Working_Hours_Per_Week"] < lower) |
    (df["Working_Hours_Per_Week"] > upper)
]

outliers
print(len(outliers))

0

In [160]:
#for Injury_History columns
Q1 = df["Injury_History"].quantile(0.25)
Q3 = df["Injury_History"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Injury_History"] < lower) |
    (df["Injury_History"] > upper)
]

outliers
print(len(outliers))

54

In [161]:
#Remove outliers from Injury History columns

df_task_five = df.copy()
df_task_five = df_task_five[
    (df['Injury_History'] >= lower) &
    (df['Injury_History'] <= upper)
]

In [162]:
#cap for Injury History columns
df_task_five['Injury_History'] = df_task_five['Injury_History'].clip(lower, upper)

In [163]:
#Log Transform for Injury History Columns

df_task_five['Injury_History'] = np.log(df_task_five['Injury_History'])

/usr/local/lib/python3.12/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

## 6. Noisy Data Filtering

### Problem Detection

Examples:

- Invalid ages
- Typing mistakes
- Random sensor noise
- Blurry images
- Irrelevant text samples

### Solutions

- Rule-based filtering
- Threshold filtering
- Quality filtering

In [164]:
#it remove invalide experience year row
df = df[df['Experience_Years'] >= 0]

In [165]:
#check Working_Hours_Per_Week
df = df[df['Working_Hours_Per_Week'] >= 0]

## 9. Data Range Validation

### Problem Detection

Examples:

- age > 150
- price < 0
- probability > 1

### Solutions

Apply business/domain rules.

In [ ]:
#for experience year data range validation
df = df[
    (df["Experience_Years"] < 0) &
    (df["Experience_Years"] > 50)
]

In [ ]:
#for working hours per week data range validation
df = df[
    (df["Working_Hours_Per_Week"] < 0) &
    (df["Working_Hours_Per_Week"] > 168)
]

## 10. Imbalanced Data Check

### Problem Detection

```python
df["target"].value_counts()
df["target"].value_counts(normalize=True)*100
```

Example:

Class 0 → 95%
Class 1 → 5%

Interpretation:

Highly Imbalanced Dataset

### Solutions

1. Oversampling
2. Undersampling
3. SMOTE
4. Class Weighting
5. Better Evaluation Metrics

In [168]:
dfLastCopy = df.copy()

In [169]:
print(dfLastCopy["Job_Risk"].value_counts())
print(dfLastCopy["Job_Risk"].value_counts(normalize=True) * 100)

Job_Risk
Low       1050
Medium     900
High       550
Name: count, dtype: int64
Job_Risk
Low       42.0
Medium    36.0
High      22.0
Name: proportion, dtype: float64

In [171]:
print(dfLastCopy["Injury_History"].value_counts())
print(dfLastCopy["Injury_History"].value_counts(normalize=True) * 100)

Injury_History
0    1387
1     845
2     214
3      44
4       8
5       1
6       1
Name: count, dtype: int64
Injury_History
0    55.48
1    33.80
2     8.56
3     1.76
4     0.32
5     0.04
6     0.04
Name: proportion, dtype: float64

In [173]:

# ---------------------
# Oversampling
# ---------------------

from sklearn.utils import resample

majority = dfLastCopy[dfLastCopy.Injury_History == 0]
minority = dfLastCopy[dfLastCopy.Injury_History == 1]

minority_up = resample(
    minority,
    replace=True,
    n_samples=len(majority),
    random_state=42
)

df_balanced = pd.concat(
    [majority, minority_up]
)

In [174]:
# ---------------------
# Undersampling
# ---------------------

majority_down = resample(
    majority,
    replace=False,
    n_samples=len(minority),
    random_state=42
)

df_under = pd.concat(
    [majority_down, minority]
)